# Generated by Django 4.1.5 on 2023-02-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgsheet', '0002_characterinformation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterinformation',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
